### ISSUE TITLE
Upgrade to Django 2.2

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/aggregator-api#74]
Refs https://github.com/DemocracyClub/aggregator-api/pull/72 ,  https://github.com/DemocracyClub/aggregator-api/pull/73

Well this one is fun..
Upgrading to django 2.2 works fine locally and in CI, but we can't deploy it to lambda. Django 2.2 bumps the minimum SQLite requirement and the deploy fails with `SQLite 3.8.3 or later is required (found 3.7.17).: ImproperlyConfigured`.

We don't actually use SQLite on this project, except to satisfy Django's need to be configured with a DB of some description. It is quite hard to get django to run with no DB configured at all (many of django's internals like admin, auth, sessions, etc expect a DB to exist/be configured, even if you're not using it).

Lambda doesn't actually provide SQLite out-of-the-box. Lambda's built-in python images/runtimes just don't include it. Zappa works around this by inserting a pre-compiled `_sqlite3.so` into the zipfile (if you `zappa package` locally, you'll see there is a `_sqlite3.so` in the output zip), which is why we can use it. The pre-compiled binary comes from https://github.com/Miserlou/lambda-packages/tree/master/lambda_packages/sqlite3 and its this (old) binary that is 3.7.17.

This problem has been noted in various issues e.g:
* https://github.com/Miserlou/lambda-packages/issues/100
* https://github.com/Miserlou/Zappa/issues/1880

but I suspect the chances of seeing a fix soon are relatively slim.

so.. where next?
First thing I've done is bump us back down to Django 1.11 which gets security patches until April 2020. That gets us back to being able to deploy. Next options are:
* Is there some crazy hair-brained way we can compile a more recent version of sqlite in a manylinux container or something and inject the shared object into the zappa package before it gets uploaded?
* Does switching from zappa to SLS give us a solution to this (we probably want to do this anyway)? If we switch to SLS, do we become responsible for bundling our own binaries for this sort of stuff?
* Given we don't actually care about using SQLite (we're just using it as a proxy for "we're not using a database" to keep django happy), is the solution to just give it a different (RDS) database somewhere to not use?
* Is it sensible to decide what we're doing about https://github.com/DemocracyClub/aggregator-api/issues/9 first? If the solution to that is we're going to use Postgres, for example, this whole problem just becomes irrelevant anyway.

**Comment by hkyq** [comment]
Any updates?

**Comment by jwilges** [comment]
I am also hitting this issue. As a newcomer to Zappa this error was initially quite obtuse.

I don't want this comment to be perceived as a brain-dead "👍me too please help!" but rather as an open inquiry to anyone more informed on Zappa's behavior here: does Zappa have a mechanism to allow users to pass in a custom SQLite binary instead of relying on the version that gets retrieved by [`extract_lambda_package('sqlite3')`](https://github.com/Miserlou/Zappa/blob/39cfb64c0acb7f2cc37d1fe9c9c2e6c19f7ff161/zappa/core.py#L670)?

If so, we (@hkyq, myself, and whoever else hits this) could easily work around this on our own, for now. If not, does the Zappa team have any plans for including newer SQLite binaries for whatever the supported platforms are?

I only just hit this error, so I have not investigated it anything beyond some "skin deep" skimming over what is happening, but I am completely happy to contribute whatever is required to resolve this properly with a better long-term solution if any Zappa contributors want to have a chat about the best way forward.

I noted two potential options above (a way to configure a custom path to the SQLite binary or perhaps updating the SQLite binary inserted from the package mentioned by @hkyq), but perhaps there are far better ways to handle this for the long run. I am new to Zappa, but this sticking point is something I would be happy to help resolve if other contributors do not have the bandwidth but are willing to have a quick chat on preference for how this would might best be resolved while fitting in with Zappa's project "style".

**Comment by hkyq** [comment]
@jwilges Zappa isn't maintained anymore, so personally I've switched. See my issue in the Zappa Rep (I'm on mobile right now), no commits since Sept and dev has been unresponsive.

**Comment by jwilges** [comment]
Oops, sorry, I did not mean to direct my comment here - I had a few GitHub tabs open and I realize this is not the right place to discuss this issue.

I do however heavily appreciate the insight in your first issue description @hkyq. I will follow up with and try to resolve this either with a discussion and pull request to the official `Zappa` and/or `lambda-packages` repository.

As for your comment on Zappa being abandoned, that sounds a bit too alarmist to me off hand, but maybe you are right. Either way, that part is not an issue for me; I am subjected to Zappa for a work project either way, so I will fix this issue regardless of whether someone can accept a pull request upstream; worst case, I will just fork the repository and solve the problem properly myself.

**Comment by jpluscplusm** [comment]
Lambda's ability to use container images as a packaging format (*not* "run Docker containers!) might help here: https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/

**Comment by symroe** [comment]
See #284 and https://github.com/DemocracyClub/aggregator-api/issues/9#issuecomment-1055331615.
